### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by ErikLentz** [pcloudcom/pclsync#4]
make
cc -Wall -Wpointer-arith -O2 -g -fno-stack-protector -fomit-frame-pointer -mtune=core2 -DP_OS_LINUX -DP_SSL_OPENSSL   -c -o pcompat.o pcompat.c
In file included from pcompat.c:35:0:
plibs.h:35:21: fatal error: sqlite3.h: No such file or directory
 #include <sqlite3.h>
                     ^
compilation terminated.
<builtin>: recipe for target 'pcompat.o' failed
make: *** [pcompat.o] Error 1

Where is the required sqlite3.h?

**Comment by ErikLentz** [comment]
Thanks.

**Comment by rzr** [comment]
This will help too:

https://github.com/pcloudcom/pclsync/pull/8
